### ISSUE TITLE
Entitlement check

### ISSUE THREAD

**Issue by FlaMango** [rjoudrey/LT-Riftless#1]
I think this might not be an issue with LT-Riftless per se; because it does work to bypass the "no headset" message in LT, however now LT just shows a "Game Failed Entitlement Check" error instead of the headset error. Any ideas?

note: additionally, I don't have a rift yet and can't try launching LT from the Oculus client — It denies the launch because it doesn't detect a headset

**Comment by rjoudrey** [comment]
This occurs after restarting one of the OVR processes (or restarting your computer). Working on a fix now

**Comment by rjoudrey** [comment]
Fixed. New release link in readme
